const { Aedes } = require('aedes');
const net = require('net');
const db = require('../models/db');

async function initMqtt(io, alertService, PORT = 1883) {
    const aedes = await Aedes.createBroker();
    const server = net.createServer(aedes.handle);

    server.listen(PORT, function () {
        console.log(`[MQTT] Aedes MQTT broker started and listening on port ${PORT}`);
    });

    aedes.on('client', (client) => {
        console.log(`[MQTT] Client connected: ${client ? client.id : client}`);
    });

    aedes.on('clientDisconnect', (client) => {
        console.log(`[MQTT] Client disconnected: ${client ? client.id : client}`);
    });

    aedes.on('publish', async function (packet, client) {
        if (!client) return; // ignore internal messages generated by Aedes itself

        const topic = packet.topic;
        const payloadStr = packet.payload.toString();
        
        // Expected topic: device/<api_key>/data
        const topicParts = topic.split('/');
        if (topicParts.length === 3 && topicParts[0] === 'device' && topicParts[2] === 'data') {
            const apiKey = topicParts[1];
            
            try {
                const deviceRes = await db.query(`
                    SELECT d.*, u.email as owner_email 
                    FROM devices d  
                    JOIN users u ON d.owner_user_id = u.id
                    WHERE d.api_key = $1
                `, [apiKey]);
                
                const device = deviceRes.rows[0];
                if (!device) {
                    console.log(`[MQTT] Invalid API KEY: ${apiKey}`);
                    return;
                }

                let data;
                try {
                    data = JSON.parse(payloadStr);
                } catch (e) {
                    console.log(`[MQTT] Invalid JSON payload from ${apiKey}`);
                    return;
                }

                const { temperature, humidity } = data;
                if (temperature === undefined || humidity === undefined) {
                    console.log(`[MQTT] Missing temperature/humidity in payload`);
                    return;
                }

                const time = new Date().toISOString();

                // 1. Insert reading into DB
                await db.query(
                    'INSERT INTO readings (device_id, temperature, humidity, timestamp) VALUES ($1, $2, $3, $4)',
                    [device.id, temperature, humidity, time]
                );

                const newReading = { device_id: device.id, temperature, humidity, timestamp: time };

                // 2. Alert Generation Logic
                if (alertService) {
                    await alertService.processReading(device, newReading, io);
                }

                // 3. Emit real-time update via Socket.io
                if (io) {
                    io.to(`device_${device.id}`).emit('new_reading', newReading);
                    io.to(`user_${device.owner_user_id}`).emit('new_reading', newReading);
                }

                console.log(`[MQTT] Received and processed data from ${device.name}: T=${temperature}, H=${humidity}`);

            } catch (err) {
                console.error('[MQTT] Error processing publish:', err);
            }
        }
    });

    return aedes;
}

module.exports = { initMqtt };
